---
# tasks file for mounted-files(nginx-php)

- name: Ensure Nginx conf.d directory exists
  file:
    path: /etc/nginx/conf.d/
    state: directory
    mode: '0755'

- name: Ensure PHP-FPM configuration directory exists
  file:
    path: /usr/local/etc/php-fpm.d/
    state: directory
    mode: '0755'

- name: Create Nginx configuration from template
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
    mode: '0644'

- name: Create PHP-FPM configuration from template
  template:
    src: php-fpm.conf.j2
    dest: "{{ php_fpm_conf_path }}"
    mode: '0644'



# we are gonna map the config file to the "conf.d" directory inside the container in docker-compose role

#docker-compose file
#
#services:
#  nginx:
#    volumes:
#      - /srv/wordpress.conf:/etc/nginx/conf.d/wordpress.conf
#      - /srv/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
