- hosts: remote_server
  vars_files:
    - ./secret-vars-vault.yml
    - ./vars.yml
  gather_facts: yes
  become: yes
  roles:
    # - 1.server_provisioning
    # - 2.remote_user
    # - 3.ssh_conf
    # - 4.mariadb
    # - 5.wordpress
    # - 6.SSL
    # - 7.docker-install
    - 8.docker-containers
    - 9.iptables