- name: create nginx conf directory
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: nginx configuration
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/conf.d/{{app_name}}.conf"

- name: create www.conf directory
  file:
    path: /etc/php/8.3/fpm/pool.d
    state: directory

- name: Copy PHP configuration file to remote server
  ansible.builtin.copy:
    src: "{{PHP_conf_path}}"
    dest: "/etc/php/8.3/fpm/pool.d/www.conf"
    owner: root
    group: root
    mode: '0644'